# Generated by Django 6.0.7 on 2026-08-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views_made',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
