# Generated by Django 6.0.7 on 2026-07-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('trade', '거래 성사'), ('stock', '입고 알림')], default='trade', max_length=10),
        ),
    ]
