# Generated by Django 6.0.7 on 2026-07-17 09:52

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    categories = ['의류', '문구, 학용품', '생활용품', '악세사리', '도서', '잡화']
    for name in categories:
        Category.objects.get_or_create(name=name)

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_view_count'),  # 이 부분은 실제 마지막 마이그레이션 파일명으로 확인 필요
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_func),
    ]